Update win2019.yml

diff --git a/.github/workflows/win2019.yml b/.github/workflows/win2019.yml
--- a/.github/workflows/win2019.yml
+++ b/.github/workflows/win2019.yml
@@ -1,4 +1,4 @@
-name: MotFull
+name: w19
 
 on: workflow_dispatch
 
@@ -24,7 +24,7 @@ jobs:
     - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
     - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "@mogus69420" -Force)
     - name: INFO VPS
-      run: tasklist | find /i "ngrok.exe" >Nul && curl -s localhost:4040/api/tunnels | jq -r .tunnels[0].public_url || echo "Unable to get NGROK tunnel, make sure NGROK_AUTH_TOKEN is correct in Settings> Secrets> Repository secret. Maybe your previous VM is still running: https://dashboard.ngrok.com/status/tunnels "
+      run: "tasklist | find /i "ngrok.exe" >Nul && curl -s localhost:4040/api/tunnels | jq -r .tunnels[0].public_url || echo "Unable to get NGROK tunnel, make sure NGROK_AUTH_TOKEN is correct in Settings> Secrets> Repository secret. Maybe your previous VM is still running: https://dashboard.ngrok.com/status/tunnels ""
       run: cmd /c ip.bat
     - name: Create Tunnel
       run: .\ngrok\ngrok.exe tcp --region ap 3389
